# Generated by Django 6.0.3 on 2026-03-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coctails_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='cocktail',
            options={'verbose_name_plural': 'Cocktails'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name_plural': 'Ingredients'},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='is_alcoholic',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='is_alcoholic',
            field=models.BooleanField(default=False),
        ),
    ]
