# Generated by Django 6.0.3 on 2026-03-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coctails_app', '0002_alter_category_options_alter_cocktail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='is_alcoholic',
            field=models.BooleanField(default=True),
        ),
    ]
